/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function isEven(n: number): boolean
export class Animal {
  name: string
  age: number
  constructor(name: string, age: number)
  getName(): string
  getAge(): Promise<number>
}
